apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "registry2registry": {{ .Values.config.registry2registry | toPrettyJson | indent 6 }}
    }